title: 找一片净土,自由的活着
description: 一个开发的后花园

baseurl: "" # the subpath of your site, e.g. /blog
pygments: true
#theme: jekyll-theme-time-machine
theme: jekyll-theme-cayman

#cayman config
google_analytics: UA-113155784-1
repository: iforgetyou/blog