title: 找一片净土,自由的活着
description: 一个开发的后花园

baseurl: "" # the subpath of your site, e.g. /blog
#theme: jekyll-theme-time-machine
theme: jekyll-theme-cayman

#cayman config
google_analytics: UA-113155784-1
repository: iforgetyou/blog

jianshu: https://www.jianshu.com/u/6fa5d5ea8b11
csdn: http://blog.csdn.net/iforgetyou